---
- name: Installation de serveur web via un playbook ansible
  hosts: node2
  remote_user: root

  tasks:
    - name: install apache
      ansible.builtin.yum:
        pkg:
          - httpd
          - net-tools
          - php
        
    - name: add user
      user:
        name: "{{ user }}"
        password: !
        shell: /bin/false

    - name: create user directory
      ansible.builtin.file:
        path: /var/www/{{ domain }}
        state: directory
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: 0755
    
    - name: customisation index.php file with phpinfo
      ansible.builtin.copy:
        src: index.php
        dest: /var/www/{{ domain }}
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: 0644

    - name: copy  virtualhost
      template:
        src: virtualhost.conf.j2
        dest: /etc/httpd/conf.d/virtualhost.conf
    
    - name: activate httpd service
      ansible.builtin.service:
        name: httpd
        enabled: true
        state: started

